### ISSUE TITLE
Add more rules config file

### ISSUE THREAD

**Issue by shino-337** [wagga40/Zircolite#1]
I see the example have rules_medium_sysmon_performance_v3.json, so where I can find it

**Comment by wagga40** [comment]
This was a test ruleset, it is the same as "rules_windows_sysmon.json" available in the rules directory of the repository : [here](https://github.com/wagga40/Zircolite/blob/master/rules/rules_windows_sysmon.json) 
Thanks for pointing it out, I will update the Readme accordingly.
You can also generate new rulesets with the genRules tools available in the tools directory.

**Comment by shino-337** [comment]
I used genrules.py to generate rules.json
python3 genRules.py --rulesdirectory=sigma/rules/windows/ --config=config/sysmon.yml --sigmac=sigma/tools/sigmac
And used zircolite with rules.json file, so when I try to view data.js of "PrivEsc_NetSvc_SessionToken_Retrival_via_localSMB_Auth_5145.evtx" with GUI, but the GUI just show only one event
![Screen Shot 2021-04-07 at 09 54 43](https://user-images.githubusercontent.com/8822078/113803707-48a3b700-9787-11eb-8f0f-15e37349ced1.png)

**Comment by wagga40** [comment]
The mini-GUI only shows detected events, it is not meant to replace tools like Splunk or ELK. If you use it on the full EVTX-ATTACK-SAMPLES repository (by specifying a directory as argument and not a evtx file) the mini-GUI will display lot of detected events. I have not test yet but the samples you used, must trigger only one rules in sigma ruleset.
By the way, thanks to you I’ve updated the rulesets to new ones yesterday 👍
