### ISSUE TITLE
Termination of EVTX processing when dealing with large EVTX files

### ISSUE THREAD

**Issue by 0xCultist** [wagga40/Zircolite#12]
I have a pretty large stack of EVTX file with actual TA artifacts in them. When running them in Zircolite it will process the 338 files (extract), however it will reach 60 ~ 90% in Processing EVTX stage and Kill the whole process. 

I was able to process around 337 different EVTX files, however I have 1 4.4GB EVTX Security file that won't be processed. 

Is there any way to process large sums of EVTX files with possible large filesize?

**Comment by wagga40** [comment]
Hi I had no problem with large EVTX files, what surprises me is the fast that the process is killed surprises me. Can you provide more details of "where" it hangs (like a terminal screenshot) ? Have you tried Zircolite with only your 4.4 GB security.evtx file ?

Zircolite can take of lot of RAM, depending on your computer available RAM may be your OS don't like it. It is possible to filter the EVTX or to use multiprocessing.

> Is there any way to process large sums of EVTX files with possible large filesize?

Yes, check here to automate the process : https://github.com/wagga40/Zircolite/blob/master/docs/Advanced.md#working-with-large-datasets

**Comment by 0xCultist** [comment]
Got it. The VM I was testing in had 4 cores, 8 GB of RAM assigned to it. Tested on a non-VM and from a 4.4 GB file there was about 32GB of RAM usage. This is mixture of RAM + SWAP. As such my previous run resulted in Memory exhaustion most likely.

**Comment by wagga40** [comment]
Thanks !
