### ISSUE TITLE
Zircolite seems to hang on extracting evtx logs

### ISSUE THREAD

**Issue by scudette** [wagga40/Zircolite#22]
I am trying Zircolite which uses the evtx parser to extract the events and it seems to get stuck while shelling out to the parser.
![Windows_Active](https://user-images.githubusercontent.com/3856546/143438617-904846f7-934d-4912-8a96-8317ee5eb19d.png)

If I copy paste the commandline into a new terminal and run the subprocess command it returns really quickly .

![Windows_Active](https://user-images.githubusercontent.com/3856546/143439019-0f6a6739-858b-48b7-85b4-da382c057022.png)

Everything is running as admin. BTW this particular event file is confirmed to be actually empty.

**Comment by wagga40** [comment]
Thanks ! 
I will check ASAP, but it is generally linked to evtx_dump (https://github.com/omerbenamram/evtx ) that get stuck by himself.

**Comment by scudette** [comment]
Running the evtx command independently works and it does not get stuck so maybe this has to do with the way pipes are created?

**Comment by wagga40** [comment]
If you pass `--noexternal` as an argument it will use the bindings instead of dropping he binary (but it is slower). Can you try please ?

**Comment by scudette** [comment]
Yes that works well. Thank you :-).  Perhaps it should be the default setting. Compared to the time taken by the rest of the code the few seconds that can be saved in this step are probably insignificant overall.

<img width="900" alt="Windows_Active" src="https://user-images.githubusercontent.com/3856546/143467257-83173c63-22fa-4953-9eb0-4ed931771634.png">

**Comment by wagga40** [comment]
Yes.

**Comment by wagga40** [comment]
You’re right, I think it will be the default behavior in next commit (and release…).
The fact that Zircolite was dropping the evtx_dump binary always seemed « messy » to me.

**Comment by wagga40** [comment]
Done.
