### ISSUE TITLE
Issue with powershell logs

### ISSUE THREAD

**Issue by cccs-jp** [wagga40/Zircolite#29]
If you take this rules for example: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/powershell/powershell_classic/posh_pc_susp_zip_compress.yml

And use sigmac as mentioned in the documentation, you will get something similar to (simplified condition):

"SELECT * FROM logs WHERE (Channel = \"Windows PowerShell\" AND HostApplication LIKE \"%hidden%\" ESCAPE '\\')"

However the ingestion of powershell event do not create a HostApplication column so the query fail (silently)

The information is found within the message column.

**Comment by wagga40** [comment]
Hi, 

sorry for the delay.
Powershell classic logs doesn't really have a `HostApplication` field, all information is stored in `<EventData><data>` : 
<img width="378" alt="Screenshot 2022-01-22 at 16 30 40" src="https://user-images.githubusercontent.com/6437862/150645007-7328dbd9-84e2-4623-96e9-ba7bfdd5d753.png">

 After the conversion with [evtx_dump](https://github.com/omerbenamram/evtx), Zircolite remap the content the `<EventData><data>` field in a `Message` field using automatic field mappings : [here](https://github.com/wagga40/Zircolite/blob/affcea1fdc7b08b52fb8967254182312d1f2d704/config/fieldMappings.json#L121)

One quick solution to your problem may be to remap the field directly in the sigmac configuration using sigma field mappings in the `Zircolite.yml` or `powershell.yml` file : 
```yaml
fieldmappings:
    HostApplication: Message
```

Please keep in mind that Powershell classic logs are difficult to handle in such scenarios. 

I think, I will leave the issue open, to handle this case in future update.
