### ISSUE TITLE
Bad interpreter

### ISSUE THREAD

**Issue by sk4la** [wagga40/Zircolite#3]
In both shebangs, the default Python interpreter is hard-coded to `/usr/bin/python3`, though my own interpreter is installed to `/usr/local/bin/python3`:

```
root@5f64728ceaf4:/mnt/host# ls -l zircolite.py
-rwxrwxr-x 1 1000 1000 20227 Apr  6 18:59 zircolite.py
root@5f64728ceaf4:/mnt/host# ./zircolite.py
bash: ./zircolite.py: /usr/bin/python3: bad interpreter: No such file or directory
root@5f64728ceaf4:/mnt/host# which python3
/usr/local/bin/python3
```

Proposal : switch the shebang from `#!/usr/bin/python3` to `#!python3` (or even `#!python`) in order to increase compatibility.

**Comment by wagga40** [comment]
For now I will stick to #!python3
