### ISSUE TITLE
Sigma Rule ID Included in Results

### ISSUE THREAD

**Issue by teddy-ROxPin** [wagga40/Zircolite#31]
Currently, when I run Zircolite using the 'exportForSplunk' template each event that is generated contains the Sigma rule title and description, along with the information from the relevant evtx entry. Would you please consider adding the Sigma rule id to each event as well? Having that unique id would be helpful with some automation efforts.

**Comment by wagga40** [comment]
Hi, 
No problem, I’ve just tested it, I will update the template and add a field in the code.

**Comment by teddy-ROxPin** [comment]
Thank you!
