### ISSUE TITLE
Add docker "latest" tag.

### ISSUE THREAD

**Issue by austinlg96** [wagga40/Zircolite#32]
Hi!

Firstly, thanks so much for putting in your time to make this tool.

Would you be open to changing the dockerhub builds so that a "latest" tag is assigned in addition to the version tag? This would allow users to grab the image without needing to pin a version.

**Comment by wagga40** [comment]
Hi, 

Thanks ! 
done with the last version of the repo : https://hub.docker.com/r/wagga40/zircolite/tags

Tell me if it is OK.

**Comment by austinlg96** [comment]
Thanks so much!

I'll give it a shot and let you know if I run into any issues.

It does seem like there is both a `latest` and a `lastest` tag that were added to dockerhub. Maybe a typo somewhere? 😅

**Comment by wagga40** [comment]
Ah yes…. Big typo. In my build script ! I will update ASAP. Thanks 🙏

**Comment by austinlg96** [comment]
For sure and thanks again!
