### ISSUE TITLE
When the --evtx input including quotes the zircolite crush

### ISSUE THREAD

**Issue by NofLevi** [wagga40/Zircolite#40]
Examples: 
--evtx C:\"ExampleFolder"\
--evtx C:\Folder\"example".txt

**Comment by wagga40** [comment]
Hi, thanks for the issue. 

It is much more a command line issue and argument parsing than a Zircolite one, have you tried single quoting the path ? 

`--evtx 'YOUR_PATH_WITH_QUOTES'`

**Comment by NofLevi10root** [comment]
Thank you for the quick comment.
You can close the issue then.
