### ISSUE TITLE
Zircolite.kape

### ISSUE THREAD

**Issue by conexioninversa** [wagga40/Zircolite#42]
Hi,
I am a big fan of the tool.  I'm lovin 'it.  works very very well. Congratulations. 
 
I wanted to inform you that I have created a module for kape so that the blue team community can use your tool.  It's been available a few hours ago at: 

https://github.com/EricZimmerman/KapeFiles/tree/master/Modules/Apps/GitHub 

Also, if you don't mind, I'll create a fork of Zircolite and add some additions that may be interesting and powerful collaborate in the improvement of Zircolite.

Great job, the community needs tools like yours to help investigate more easily.  Thank you

**Comment by wagga40** [comment]
That's very nice of you !

You can fork the project, it is one of the reason of posting it on GitHub.
Pull Requests will be welcomed warmly 😁
