### ISSUE TITLE
Terminal Color error

### ISSUE THREAD

**Issue by frack113** [wagga40/Zircolite#47]
When get an error in Zircolite the color of the terminal is not restored

![image](https://user-images.githubusercontent.com/62423083/211200358-88a2b4bf-7a3c-4cf0-b848-c8549a84e08a.png)

**Comment by wagga40** [comment]
Solved in this [commit](https://github.com/wagga40/Zircolite/commit/2ca921cfc5736b8f2a463776a7db3621a7889715)
