### ISSUE TITLE
Zircolite v2.9.7 On the fly rules conversion

### ISSUE THREAD

**Issue by frack113** [wagga40/Zircolite#48]
From documentation:
```
Since Zircolite 2.2.0, if you have sigmatools >= 0.21, Zircolite is able to convert the rules on-the-fly if you provide a SIGMA config file and the sigmac path. It is very convenient for testing but you should avoid it since this is slower :
```

But they are no option `--sigma` or `--sigmac` valid

**Comment by wagga40** [comment]
Since it was depending on a now deprecated sigmac, it was removed. But the docs have not been updated.
I will remove this part.

**Comment by wagga40** [comment]
Solved in this [commit](https://github.com/wagga40/Zircolite/commit/2ca921cfc5736b8f2a463776a7db3621a7889715)
