### ISSUE TITLE
[FR] The possibility to remove a EVTX or File after analyze

### ISSUE THREAD

**Issue by V1D1AN** [wagga40/Zircolite#51]
Hello Zircolite team,

Can you add a feature for Zircolite, even if this feature will not be understood by everyone, can you add the possibility to delete the file after its analysis.
A bit like "logstash" with its "file_completed_action => "delete" option

A option like "--remove".

Thanks for your software and your jobs

@+ wagga :)

**Comment by wagga40** [comment]
Hello, 
Thanks for your request !
Done in https://github.com/wagga40/Zircolite/commit/8f39b6bd447b2dcc3aaecbd433b91c4d77873b64
