### ISSUE TITLE
ModuleNotFoundError: No module named 'elasticsearch'

### ISSUE THREAD

**Issue by dalifig** [wagga40/Zircolite#56]

**Comment by wagga40** [comment]
Hi,
I’m assuming you use the python version.

Did you install dependencies in `requirements.txt` with : `pip3 install -r requirements.txt` or `pip install -r requirements.txt` ?

**Comment by dalifig** [comment]
Thank you so much for the quick response
I tried to delete my issue because I already fixed it but I don't think
github gave me the authority to delete my comment.
I did the  pip3 install -r requirements.txt already but the issue was still
there, what fixed it for me was that I just added sudo to the command and
executed it as administrator.

**Comment by wagga40** [comment]
Ok 👍🏻
