### ISSUE TITLE
'consoleLogger' is not defined

### ISSUE THREAD

**Issue by MariasStory** [wagga40/Zircolite#6]
Hi,
Thank you for the cool solution.

I am trying to use zircolite_lin_nuitka_embedded v 1.4.1 on linux and getting this error:
```
Traceback (most recent call last):
  File "/tmp/.mount_zircol5dxM6c/zircolite.py", line 393, in <module>
  File "/tmp/.mount_zircol5dxM6c/zircolite.py", line 251, in quitOnError
NameError: name 'consoleLogger' is not defined
```

**Comment by wagga40** [comment]
**Thanks for the feedback. I've updated the release.**
Your issue allowed me to correct another bug in embedded versions. The new binaries have been uploaded.

Please note that Zircolite v2 will have allow user to generate their own embedded versions.
