### ISSUE TITLE
KeyError: 'SystemTime' in zircolite.py -- suggested fix

### ISSUE THREAD

**Issue by Hullgj** [wagga40/Zircolite#7]
Running this on Windows 10, I get an error **KeyError: 'SystemTime'** on  Line 229 of zircolite.py. I get the same error message when running it with zircolite_legacy.py and the Windows release version 2.0.0. I fixed my local version with a check for the key SystemTime, as shown below:

This creates a JSON exception if there is no SystemTime in the JSONLine.
```
if self.timeAfter != "1970-01-01T00:00:00" and self.timeBefore != "9999-12-12T23:59:59":
      timestamp = time.strptime(JSONLine["SystemTime"].split(".")[0].replace("Z",""), '%Y-%m-%dT%H:%M:%S')
      if timestamp > self.timeAfter and timestamp < self.timeBefore:
          JSONOutput.append(JSONLine)
```

Can you update it to something like this, which checks if that key exists:
```
if self.timeAfter != "1970-01-01T00:00:00" and self.timeBefore != "9999-12-12T23:59:59" and "SystemTime" in JSONLine:
    timestamp = time.strptime(JSONLine["SystemTime"].split(".")[0].replace("Z",""), '%Y-%m-%dT%H:%M:%S')
    if timestamp > self.timeAfter and timestamp < self.timeBefore:
        JSONOutput.append(JSONLine)
```

**Comment by wagga40** [comment]
Thank you, I don't really know how I let this slip. 
It seems that all EVTX I do tests with have this field.
I've just pushed the update with your fix, release are building and will be pushed when done.
Don't hesitate to do a PR next time 👍

**Comment by Hullgj** [comment]
Thanks!
