### ISSUE TITLE
Benchmarks & speeds and improvements

### ISSUE THREAD

**Issue by MyraBaba** [wagga40/Zircolite#90]
Hi,

I cam a cross your project today and wll have a try. 

We wonder the benchmarks of the processing 2000 sigma rules over 5gig log ie ? Do you have such benchmarks ? 

How we can improve the processing speed ? We can re-write critical part in c++ if it helps ? 

Best

**Comment by wagga40** [comment]
Hi, 

I just ran Zircolite on **15 GB of EVTX files** (Sysmon, Security etc.) : 
- With multiple files and the use of GNU Parallel, It took **1 min 41 s** with **2723 rules**
- By using Zircolite on all the files at once, it took **9 min 54s** with **2723 rules** (from the sigma official repository) on Python 3.10 (newer version of Python will be faster). 

For the same dataset, Hayabusa took 8 min. Both tools use alot of memory.

The main part of Zircolite (the detection process) is only performed on one CPU Core. I am currently working on a way to speed things up by using all the cores.

**Comment by MyraBaba** [comment]
Almost same as hayabusa ..

Below 15 min is not bad at all. The memory usage is high 15GB EVTX ~30GB - 45GB memory

I will look closely the code. I assume only one python file.


Best

**Comment by wagga40** [comment]
Thanks.

> The memory usage is high 15GB EVTX ~30GB - 45GB memory

For the aforementioned test, without GNU Parallel, memory usage peaked at 25 GB.

**Comment by wagga40** [comment]
Just to let you know that the future version of zircolite takes **1 min 51 s** to execute with the same **15 GB** dataset on the very same computer.

**Comment by MyraBaba** [comment]
@wagga40  is it 1 core or multiple core result 1 min 51 s ?

sqlite insert looks last longer..

**Comment by wagga40** [comment]
multiple cores.

**Comment by wagga40** [comment]
> sqlite insert looks last longer..

You should not focus to much on SQLite Insertion, on the actual version (single core) for the same dataset takes only 25 secs...

**Comment by MyraBaba** [comment]
When are you going to release new version :) ?

**Comment by wagga40** [comment]
I still have some things I need to adjust but I think this week end.
