### ISSUE TITLE
Trojan Detected in Windows Package

### ISSUE THREAD

**Issue by N45gu1** [wagga40/Zircolite#92]
Hi,
I am encountering an issue with version 2.30.1 of the software on Windows. A trojan is detected during the package generation.
Are you able to reproduce this malfunction?
Thanks in advance

**Comment by wagga40** [comment]
Hi, 

this is a quite a common problem with Windows, sometimes the rulesets are detected as malicious, sometimes the JS inside the mini-gui.

The best way to avoid this kind of problem is to add the Zircolite folder to AV exceptions. This is what I do when I test the release.
