### ISSUE TITLE
Update Zircolite version string

### ISSUE THREAD

**Issue by evild3ad** [wagga40/Zircolite#93]
`.\zircolite.exe --version` shows 'Zircolite - v2.30.0' instead of 'Zircolite - v2.30.1'

... irritates the auto-updater of my MemProcFS-Analyzer. :wink:

Thank you!

**Comment by wagga40** [comment]
Oh sh… you are right. Sorry, will update ASAP.

**Comment by wagga40** [comment]
Hi sorry for the delay... it should be OK.

**Comment by evild3ad** [comment]
Works! 💪
