### ISSUE TITLE
Invalid Argument 

### ISSUE THREAD

**Issue by MyraBaba** [wagga40/Zircolite#94]
python .\zircolite.py  --evtx .\7\ --rules C:\PURE7\rules.json

Traceback (most recent call last):
  File "C:\RE7\Zircolite\zircolite.py", line 2713, in <module>
    main()
  File "C:\RE7\Zircolite\zircolite.py", line 2622, in main
    zircoliteCore.run(LogJSONList, saveToFile=args.keepflat, args_config=args)
  File "C:\RE7\Zircolite\zircolite.py", line 1227, in run
    flattener.runAll(EVTXJSONList)
  File "C:\RE7\Zircolite\zircolite.py", line 830, in runAll
    results = self.run(evtxJSON)
  File "C:\RE7\Zircolite\zircolite.py", line 777, in run
    with open(str(file), "r", encoding="utf-8") as JSONFile:
OSError: [Errno 22] Invalid argument: 'tmp-6W5YO034\\ID400-800-CrackMapExec payload execution.evtx-R0YQ824M.json'

**Comment by MyraBaba** [comment]
@wagga40 

Hi I have good case for you. rules.json and evtx files. hayabusa took 390 sec zircolite took 1400sec. 

I can share the data privately if you want to examine. 

Best

**Comment by wagga40** [comment]
> I can share the data privately if you want to examine.

yeah I’m interested, how do you want to proceed ?

**Comment by MyraBaba** [comment]
give me your email pls

**Comment by MyraBaba** [comment]
@wagga40  

I can send links for rules and evtx zip for test to your email.

As far as I see its take too long for some queries. 

ie: 17.000 result.. takes too long to query. 

hayabusa always around 4 min - 5 min. 



<img width="917" alt="Screen Shot 2024-10-31 at 16 28 22" src="https://github.com/user-attachments/assets/298b697b-8dc6-440d-bd5e-385128ed6136">
<img width="756" alt="Screen Shot 2024-10-31 at 16 23 41" src="https://github.com/user-attachments/assets/13990936-2bce-405c-af48-441b9d6dcc43">

**Comment by MyraBaba** [comment]
@wagga40 

more diagnosis clues:

same log and same json rules:

on my vmware windows 10  took 297 sconds

on another server ; vmware win server 2019 took 14500 seconds. !

both machine hayabusa 300 seconds

**Comment by wagga40** [comment]
email : seringues-06.phyla@icloud.com

did you try with the v3 version in the dev branch ? https://github.com/wagga40/Zircolite/tree/v3.0 (very unstable, csu output not working)

**Comment by MyraBaba** [comment]
is zircolite.py or zircolite_dev.py ?

Only gettin above file is enough or need full repo ? 

Will prepare you VMware image for same test

Best

**Comment by wagga40** [comment]
You should use zircolite_dev.py

Normally it should work only with this file

**Comment by MyraBaba** [comment]
Hayabusa Almost 5-7 times faster . But I believe we can catch its speed.

PS: I am preparing the VMware image


	
Best

**Comment by wagga40** [comment]
I sent you an email, could you share your samples ?

**Comment by wagga40** [comment]
Whith the news version (https://github.com/wagga40/Zircolite/tree/v3.0) of Zircolite and default ruleset or your ruleset, it took 23 sec.

RAM and Storage speed (SSD vs non SSD) can change the results.

![Example](https://github.com/user-attachments/assets/ff5a2a0c-e3ac-4a72-8b35-946c2030b15f)

**Comment by wagga40** [comment]
I've tested in a Windows VM. It took 44 sec
